apiVersion: v1
kind: ReplicationController
metadata:
  name: myrcpod
spec:
  replicas: 3 
  selector:
    team: dev
  template:
    metadata:
     name: mypod
     labels:
      team: dev
      city: Jpr
    spec:
      containers:
      - name: myday
        image: httpd

