Equality based selectors are little bit old
and it becomes complex when we have a lots of labels.
So, we use set-based selectors.


apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs1
spec:
  replicas: 2
  selector:
   matchLabels:
     team: "dev"
   matchExpressions:
     - { key: dc, operator: In, values: [ "IN" ] }
     - { key: region, operator: In, values: [ "US" ] }

  template:
    metadata:
      name: "mypod"
      labels:
        dc: IN
        region: US
        team: dev
    spec:
      containers:
      - name: myrccont1
        image: httpd
