apiVersion: v1
kind: ReplicationController
metadata:
 name: myrc
spec:
 replicas: 1
 selector:
   team: "dev"
 template:
    metadata:
      name: mypod
      labels:
         team: "dev"
    spec:
      containers:
      - name: myc1
        image: vimal13/apache-webserver-php
