apiVersion: v1
kind: ReplicationController
metadata:
 name: myrc2
spec:
 replicas: 1
 selector:
   team: "ops"
 template:
    metadata:
      name: mypod
      labels:
         team: "ops"
    spec:
      containers:
      - name: myc2
        image: vimal13/apache-webserver-php
