apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: eric-user-montoring-binding
 namespace: testing
subjects:
- kind: User
  name: eric
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: mymonitor-role
  apiGroup: rbac.authorization.k8s.io
