apiVersion: v1
kind: Pod
metadata:
  name: "mypod"

spec:
 containers:
 - name: "myc2"
   image: "vimal13/apache-webserver-php"
   volumeMounts:
   - mountPath: /etc/httpd/conf.d/
     name: mycm2
 volumes: 
 - configMap:
     name: newcm2
   name: mycm2
